### ISSUE TITLE
Clang

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-luasocket#1]
needs clang listed for Windows in the mime extension

**Comment by britzl** [comment]
The use-clang flag needs to be added to the project app manifest, not the extension manifest. I've verified that defold-luasocket bundles for Windows with use-clang set to true, but when you use this project as a dependency you need to add it to your project's app manifest yourself.

**Comment by subsoap** [comment]
Ah! I thought it would go in ext.manifest too
